export default fonts = {
    Quicksand:{
        bold:'Quicksand-Bold',
        ligth:'Quicksand-Light',
        medium:'Quicksand-Medium',
        regular:'Quicksand-Regular'
    },
    Roboto:{
        black:'Roboto-Black',
        blackItalic:'Roboto-BlackItalic',
        bold:'Roboto-Bold',
        boldItalic:'Roboto-BoldItalic',
        italic:'Roboto-Italic',
        light:'Roboto-Light',
        lightItalic:'Roboto-LightItalic',
        medium:'Roboto-Medium',
        mediumItalic:'Roboto-MediumItalic',
        regular:'Roboto-Regular',
        thin:'Roboto-Thin',
        thinItalic:'Roboto-ThinItalic',
    },
    Comfortaa:{
        bold:'Comfortaa-Bold',
        ligth:'Comfortaa-Light',
        regular:'Comfortaa-Regular'
    },
}