// flow-typed signature: 93b93166683be7d970cdf0a9a9b86ae3
// flow-typed version: <<STUB>>/eslint-config-recommended_v^4.0.0/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-recommended'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-recommended' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-recommended/esnext/index' {
  declare module.exports: any;
}

declare module 'eslint-config-recommended/esnext/style-guide' {
  declare module.exports: any;
}

declare module 'eslint-config-recommended/node/index' {
  declare module.exports: any;
}

declare module 'eslint-config-recommended/node/style-guide' {
  declare module.exports: any;
}

declare module 'eslint-config-recommended/react-native/index' {
  declare module.exports: any;
}

declare module 'eslint-config-recommended/react-native/style-guide' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-recommended/esnext/index.js' {
  declare module.exports: $Exports<'eslint-config-recommended/esnext/index'>;
}
declare module 'eslint-config-recommended/esnext/style-guide.js' {
  declare module.exports: $Exports<'eslint-config-recommended/esnext/style-guide'>;
}
declare module 'eslint-config-recommended/node/index.js' {
  declare module.exports: $Exports<'eslint-config-recommended/node/index'>;
}
declare module 'eslint-config-recommended/node/style-guide.js' {
  declare module.exports: $Exports<'eslint-config-recommended/node/style-guide'>;
}
declare module 'eslint-config-recommended/react-native/index.js' {
  declare module.exports: $Exports<'eslint-config-recommended/react-native/index'>;
}
declare module 'eslint-config-recommended/react-native/style-guide.js' {
  declare module.exports: $Exports<'eslint-config-recommended/react-native/style-guide'>;
}
