// flow-typed signature: e66b079cb559468fd60b7fe4d9a52f00
// flow-typed version: <<STUB>>/expo_v^32.0.0/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo/AppEntry' {
  declare module.exports: any;
}

declare module 'expo/bin/cli' {
  declare module.exports: any;
}

declare module 'expo/build/Amplitude/Amplitude' {
  declare module.exports: any;
}

declare module 'expo/build/Amplitude/ExponentAmplitude' {
  declare module.exports: any;
}

declare module 'expo/build/Amplitude/ExponentAmplitude.web' {
  declare module.exports: any;
}

declare module 'expo/build/apisAreAvailable' {
  declare module.exports: any;
}

declare module 'expo/build/AR' {
  declare module.exports: any;
}

declare module 'expo/build/AuthSession' {
  declare module.exports: any;
}

declare module 'expo/build/av/Audio' {
  declare module.exports: any;
}

declare module 'expo/build/av/Audio/AudioAvailability' {
  declare module.exports: any;
}

declare module 'expo/build/av/Audio/Recording' {
  declare module.exports: any;
}

declare module 'expo/build/av/Audio/Sound' {
  declare module.exports: any;
}

declare module 'expo/build/av/AV' {
  declare module.exports: any;
}

declare module 'expo/build/av/Video' {
  declare module.exports: any;
}

declare module 'expo/build/av/Video.web' {
  declare module.exports: any;
}

declare module 'expo/build/Branch' {
  declare module.exports: any;
}

declare module 'expo/build/Branch.web' {
  declare module.exports: any;
}

declare module 'expo/build/Brightness' {
  declare module.exports: any;
}

declare module 'expo/build/Calendar' {
  declare module.exports: any;
}

declare module 'expo/build/DangerZone' {
  declare module.exports: any;
}

declare module 'expo/build/DocumentPicker' {
  declare module.exports: any;
}

declare module 'expo/build/effects/BlurView.android' {
  declare module.exports: any;
}

declare module 'expo/build/effects/BlurView.ios' {
  declare module.exports: any;
}

declare module 'expo/build/effects/BlurView.web' {
  declare module.exports: any;
}

declare module 'expo/build/effects/LinearGradient' {
  declare module.exports: any;
}

declare module 'expo/build/effects/NativeLinearGradient.android' {
  declare module.exports: any;
}

declare module 'expo/build/effects/NativeLinearGradient.ios' {
  declare module.exports: any;
}

declare module 'expo/build/effects/NativeLinearGradient.web' {
  declare module.exports: any;
}

declare module 'expo/build/environment/logging' {
  declare module.exports: any;
}

declare module 'expo/build/environment/validate' {
  declare module.exports: any;
}

declare module 'expo/build/ErrorRecovery/ErrorRecovery' {
  declare module.exports: any;
}

declare module 'expo/build/ErrorRecovery/ExponentErrorRecovery' {
  declare module.exports: any;
}

declare module 'expo/build/ErrorRecovery/ExponentErrorRecovery.web' {
  declare module.exports: any;
}

declare module 'expo/build/Expo' {
  declare module.exports: any;
}

declare module 'expo/build/facebook-ads/AdIconView' {
  declare module.exports: any;
}

declare module 'expo/build/facebook-ads/AdMediaView' {
  declare module.exports: any;
}

declare module 'expo/build/facebook-ads/AdSettings' {
  declare module.exports: any;
}

declare module 'expo/build/facebook-ads/AdTriggerView' {
  declare module.exports: any;
}

declare module 'expo/build/facebook-ads/BannerAd' {
  declare module.exports: any;
}

declare module 'expo/build/facebook-ads/index' {
  declare module.exports: any;
}

declare module 'expo/build/facebook-ads/index.web' {
  declare module.exports: any;
}

declare module 'expo/build/facebook-ads/InterstitialAdManager' {
  declare module.exports: any;
}

declare module 'expo/build/facebook-ads/NativeAdsManager' {
  declare module.exports: any;
}

declare module 'expo/build/facebook-ads/withNativeAd' {
  declare module.exports: any;
}

declare module 'expo/build/Facebook/ExponentFacebook' {
  declare module.exports: any;
}

declare module 'expo/build/Facebook/ExponentFacebook.web' {
  declare module.exports: any;
}

declare module 'expo/build/Facebook/Facebook' {
  declare module.exports: any;
}

declare module 'expo/build/Fingerprint' {
  declare module.exports: any;
}

declare module 'expo/build/GestureHandler' {
  declare module.exports: any;
}

declare module 'expo/build/GestureHandler.web' {
  declare module.exports: any;
}

declare module 'expo/build/Google/Google' {
  declare module.exports: any;
}

declare module 'expo/build/Haptic/ExponentHaptic' {
  declare module.exports: any;
}

declare module 'expo/build/Haptic/ExponentHaptic.web' {
  declare module.exports: any;
}

declare module 'expo/build/Haptic/Haptic' {
  declare module.exports: any;
}

declare module 'expo/build/Icon' {
  declare module.exports: any;
}

declare module 'expo/build/ImageManipulator/ExponentImageManipulator' {
  declare module.exports: any;
}

declare module 'expo/build/ImageManipulator/ExponentImageManipulator.web' {
  declare module.exports: any;
}

declare module 'expo/build/ImageManipulator/ImageManipulator' {
  declare module.exports: any;
}

declare module 'expo/build/ImagePicker/ExponentImagePicker' {
  declare module.exports: any;
}

declare module 'expo/build/ImagePicker/ExponentImagePicker.web' {
  declare module.exports: any;
}

declare module 'expo/build/ImagePicker/ImagePicker' {
  declare module.exports: any;
}

declare module 'expo/build/IntentLauncherAndroid/ExponentIntentLauncher' {
  declare module.exports: any;
}

declare module 'expo/build/IntentLauncherAndroid/ExponentIntentLauncher.web' {
  declare module.exports: any;
}

declare module 'expo/build/IntentLauncherAndroid/IntentLauncherAndroid' {
  declare module.exports: any;
}

declare module 'expo/build/KeepAwake/ExponentKeepAwake' {
  declare module.exports: any;
}

declare module 'expo/build/KeepAwake/ExponentKeepAwake.web' {
  declare module.exports: any;
}

declare module 'expo/build/KeepAwake/index' {
  declare module.exports: any;
}

declare module 'expo/build/launch/AppLoading' {
  declare module.exports: any;
}

declare module 'expo/build/launch/AppLoadingNativeWrapper' {
  declare module.exports: any;
}

declare module 'expo/build/launch/registerRootComponent' {
  declare module.exports: any;
}

declare module 'expo/build/launch/registerRootComponent.web' {
  declare module.exports: any;
}

declare module 'expo/build/launch/RootErrorBoundary' {
  declare module.exports: any;
}

declare module 'expo/build/launch/SplashScreen' {
  declare module.exports: any;
}

declare module 'expo/build/launch/withExpoRoot' {
  declare module.exports: any;
}

declare module 'expo/build/Linking' {
  declare module.exports: any;
}

declare module 'expo/build/Localization' {
  declare module.exports: any;
}

declare module 'expo/build/logs/format/ReactNodeFormatter' {
  declare module.exports: any;
}

declare module 'expo/build/logs/Logs' {
  declare module.exports: any;
}

declare module 'expo/build/logs/LogSerialization' {
  declare module.exports: any;
}

declare module 'expo/build/logs/RemoteConsole' {
  declare module.exports: any;
}

declare module 'expo/build/logs/RemoteLogging' {
  declare module.exports: any;
}

declare module 'expo/build/logs/symbolicateStackTrace' {
  declare module.exports: any;
}

declare module 'expo/build/logs/symbolicateStackTrace.web' {
  declare module.exports: any;
}

declare module 'expo/build/MailComposer/ExponentMailComposer' {
  declare module.exports: any;
}

declare module 'expo/build/MailComposer/ExponentMailComposer.web' {
  declare module.exports: any;
}

declare module 'expo/build/MailComposer/MailComposer' {
  declare module.exports: any;
}

declare module 'expo/build/MailComposer/MailComposer.types' {
  declare module.exports: any;
}

declare module 'expo/build/Notifications/ExponentNotifications' {
  declare module.exports: any;
}

declare module 'expo/build/Notifications/ExponentNotifications.web' {
  declare module.exports: any;
}

declare module 'expo/build/Notifications/Notifications' {
  declare module.exports: any;
}

declare module 'expo/build/Payments' {
  declare module.exports: any;
}

declare module 'expo/build/Pedometer' {
  declare module.exports: any;
}

declare module 'expo/build/ScreenOrientation/ExponentScreenOrientation' {
  declare module.exports: any;
}

declare module 'expo/build/ScreenOrientation/ExponentScreenOrientation.web' {
  declare module.exports: any;
}

declare module 'expo/build/ScreenOrientation/ScreenOrientation' {
  declare module.exports: any;
}

declare module 'expo/build/SecureStore/ExponentSecureStore' {
  declare module.exports: any;
}

declare module 'expo/build/SecureStore/ExponentSecureStore.web' {
  declare module.exports: any;
}

declare module 'expo/build/SecureStore/SecureStore' {
  declare module.exports: any;
}

declare module 'expo/build/Speech/ExponentSpeech' {
  declare module.exports: any;
}

declare module 'expo/build/Speech/ExponentSpeech.web' {
  declare module.exports: any;
}

declare module 'expo/build/Speech/Speech' {
  declare module.exports: any;
}

declare module 'expo/build/Speech/Speech.types' {
  declare module.exports: any;
}

declare module 'expo/build/SQLite' {
  declare module.exports: any;
}

declare module 'expo/build/SQLite.web' {
  declare module.exports: any;
}

declare module 'expo/build/StoreReview/ExponentStoreReview' {
  declare module.exports: any;
}

declare module 'expo/build/StoreReview/ExponentStoreReview.web' {
  declare module.exports: any;
}

declare module 'expo/build/StoreReview/StoreReview' {
  declare module.exports: any;
}

declare module 'expo/build/Svg' {
  declare module.exports: any;
}

declare module 'expo/build/Svg.web' {
  declare module.exports: any;
}

declare module 'expo/build/takeSnapshotAsync' {
  declare module.exports: any;
}

declare module 'expo/build/timer/polyfillNextTick' {
  declare module.exports: any;
}

declare module 'expo/build/Updates/ExponentUpdates' {
  declare module.exports: any;
}

declare module 'expo/build/Updates/ExponentUpdates.web' {
  declare module.exports: any;
}

declare module 'expo/build/Updates/Updates' {
  declare module.exports: any;
}

declare module 'expo/build/Util' {
  declare module.exports: any;
}

declare module 'expo/build/web/Network/RCTNetworking' {
  declare module.exports: any;
}

declare module 'expo/build/web/Performance/Systrace' {
  declare module.exports: any;
}

declare module 'expo/build/web/Utilities/HMRLoadingView' {
  declare module.exports: any;
}

declare module 'expo/build/WebBrowser/ExponentWebBrowser' {
  declare module.exports: any;
}

declare module 'expo/build/WebBrowser/ExponentWebBrowser.web' {
  declare module.exports: any;
}

declare module 'expo/build/WebBrowser/WebBrowser' {
  declare module.exports: any;
}

declare module 'expo/tools/hashAssetFiles' {
  declare module.exports: any;
}

declare module 'expo/tools/LogReporter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo/AppEntry.js' {
  declare module.exports: $Exports<'expo/AppEntry'>;
}
declare module 'expo/bin/cli.js' {
  declare module.exports: $Exports<'expo/bin/cli'>;
}
declare module 'expo/build/Amplitude/Amplitude.js' {
  declare module.exports: $Exports<'expo/build/Amplitude/Amplitude'>;
}
declare module 'expo/build/Amplitude/ExponentAmplitude.js' {
  declare module.exports: $Exports<'expo/build/Amplitude/ExponentAmplitude'>;
}
declare module 'expo/build/Amplitude/ExponentAmplitude.web.js' {
  declare module.exports: $Exports<'expo/build/Amplitude/ExponentAmplitude.web'>;
}
declare module 'expo/build/apisAreAvailable.js' {
  declare module.exports: $Exports<'expo/build/apisAreAvailable'>;
}
declare module 'expo/build/AR.js' {
  declare module.exports: $Exports<'expo/build/AR'>;
}
declare module 'expo/build/AuthSession.js' {
  declare module.exports: $Exports<'expo/build/AuthSession'>;
}
declare module 'expo/build/av/Audio.js' {
  declare module.exports: $Exports<'expo/build/av/Audio'>;
}
declare module 'expo/build/av/Audio/AudioAvailability.js' {
  declare module.exports: $Exports<'expo/build/av/Audio/AudioAvailability'>;
}
declare module 'expo/build/av/Audio/Recording.js' {
  declare module.exports: $Exports<'expo/build/av/Audio/Recording'>;
}
declare module 'expo/build/av/Audio/Sound.js' {
  declare module.exports: $Exports<'expo/build/av/Audio/Sound'>;
}
declare module 'expo/build/av/AV.js' {
  declare module.exports: $Exports<'expo/build/av/AV'>;
}
declare module 'expo/build/av/Video.js' {
  declare module.exports: $Exports<'expo/build/av/Video'>;
}
declare module 'expo/build/av/Video.web.js' {
  declare module.exports: $Exports<'expo/build/av/Video.web'>;
}
declare module 'expo/build/Branch.js' {
  declare module.exports: $Exports<'expo/build/Branch'>;
}
declare module 'expo/build/Branch.web.js' {
  declare module.exports: $Exports<'expo/build/Branch.web'>;
}
declare module 'expo/build/Brightness.js' {
  declare module.exports: $Exports<'expo/build/Brightness'>;
}
declare module 'expo/build/Calendar.js' {
  declare module.exports: $Exports<'expo/build/Calendar'>;
}
declare module 'expo/build/DangerZone.js' {
  declare module.exports: $Exports<'expo/build/DangerZone'>;
}
declare module 'expo/build/DocumentPicker.js' {
  declare module.exports: $Exports<'expo/build/DocumentPicker'>;
}
declare module 'expo/build/effects/BlurView.android.js' {
  declare module.exports: $Exports<'expo/build/effects/BlurView.android'>;
}
declare module 'expo/build/effects/BlurView.ios.js' {
  declare module.exports: $Exports<'expo/build/effects/BlurView.ios'>;
}
declare module 'expo/build/effects/BlurView.web.js' {
  declare module.exports: $Exports<'expo/build/effects/BlurView.web'>;
}
declare module 'expo/build/effects/LinearGradient.js' {
  declare module.exports: $Exports<'expo/build/effects/LinearGradient'>;
}
declare module 'expo/build/effects/NativeLinearGradient.android.js' {
  declare module.exports: $Exports<'expo/build/effects/NativeLinearGradient.android'>;
}
declare module 'expo/build/effects/NativeLinearGradient.ios.js' {
  declare module.exports: $Exports<'expo/build/effects/NativeLinearGradient.ios'>;
}
declare module 'expo/build/effects/NativeLinearGradient.web.js' {
  declare module.exports: $Exports<'expo/build/effects/NativeLinearGradient.web'>;
}
declare module 'expo/build/environment/logging.js' {
  declare module.exports: $Exports<'expo/build/environment/logging'>;
}
declare module 'expo/build/environment/validate.js' {
  declare module.exports: $Exports<'expo/build/environment/validate'>;
}
declare module 'expo/build/ErrorRecovery/ErrorRecovery.js' {
  declare module.exports: $Exports<'expo/build/ErrorRecovery/ErrorRecovery'>;
}
declare module 'expo/build/ErrorRecovery/ExponentErrorRecovery.js' {
  declare module.exports: $Exports<'expo/build/ErrorRecovery/ExponentErrorRecovery'>;
}
declare module 'expo/build/ErrorRecovery/ExponentErrorRecovery.web.js' {
  declare module.exports: $Exports<'expo/build/ErrorRecovery/ExponentErrorRecovery.web'>;
}
declare module 'expo/build/Expo.js' {
  declare module.exports: $Exports<'expo/build/Expo'>;
}
declare module 'expo/build/facebook-ads/AdIconView.js' {
  declare module.exports: $Exports<'expo/build/facebook-ads/AdIconView'>;
}
declare module 'expo/build/facebook-ads/AdMediaView.js' {
  declare module.exports: $Exports<'expo/build/facebook-ads/AdMediaView'>;
}
declare module 'expo/build/facebook-ads/AdSettings.js' {
  declare module.exports: $Exports<'expo/build/facebook-ads/AdSettings'>;
}
declare module 'expo/build/facebook-ads/AdTriggerView.js' {
  declare module.exports: $Exports<'expo/build/facebook-ads/AdTriggerView'>;
}
declare module 'expo/build/facebook-ads/BannerAd.js' {
  declare module.exports: $Exports<'expo/build/facebook-ads/BannerAd'>;
}
declare module 'expo/build/facebook-ads/index.js' {
  declare module.exports: $Exports<'expo/build/facebook-ads/index'>;
}
declare module 'expo/build/facebook-ads/index.web.js' {
  declare module.exports: $Exports<'expo/build/facebook-ads/index.web'>;
}
declare module 'expo/build/facebook-ads/InterstitialAdManager.js' {
  declare module.exports: $Exports<'expo/build/facebook-ads/InterstitialAdManager'>;
}
declare module 'expo/build/facebook-ads/NativeAdsManager.js' {
  declare module.exports: $Exports<'expo/build/facebook-ads/NativeAdsManager'>;
}
declare module 'expo/build/facebook-ads/withNativeAd.js' {
  declare module.exports: $Exports<'expo/build/facebook-ads/withNativeAd'>;
}
declare module 'expo/build/Facebook/ExponentFacebook.js' {
  declare module.exports: $Exports<'expo/build/Facebook/ExponentFacebook'>;
}
declare module 'expo/build/Facebook/ExponentFacebook.web.js' {
  declare module.exports: $Exports<'expo/build/Facebook/ExponentFacebook.web'>;
}
declare module 'expo/build/Facebook/Facebook.js' {
  declare module.exports: $Exports<'expo/build/Facebook/Facebook'>;
}
declare module 'expo/build/Fingerprint.js' {
  declare module.exports: $Exports<'expo/build/Fingerprint'>;
}
declare module 'expo/build/GestureHandler.js' {
  declare module.exports: $Exports<'expo/build/GestureHandler'>;
}
declare module 'expo/build/GestureHandler.web.js' {
  declare module.exports: $Exports<'expo/build/GestureHandler.web'>;
}
declare module 'expo/build/Google/Google.js' {
  declare module.exports: $Exports<'expo/build/Google/Google'>;
}
declare module 'expo/build/Haptic/ExponentHaptic.js' {
  declare module.exports: $Exports<'expo/build/Haptic/ExponentHaptic'>;
}
declare module 'expo/build/Haptic/ExponentHaptic.web.js' {
  declare module.exports: $Exports<'expo/build/Haptic/ExponentHaptic.web'>;
}
declare module 'expo/build/Haptic/Haptic.js' {
  declare module.exports: $Exports<'expo/build/Haptic/Haptic'>;
}
declare module 'expo/build/Icon.js' {
  declare module.exports: $Exports<'expo/build/Icon'>;
}
declare module 'expo/build/ImageManipulator/ExponentImageManipulator.js' {
  declare module.exports: $Exports<'expo/build/ImageManipulator/ExponentImageManipulator'>;
}
declare module 'expo/build/ImageManipulator/ExponentImageManipulator.web.js' {
  declare module.exports: $Exports<'expo/build/ImageManipulator/ExponentImageManipulator.web'>;
}
declare module 'expo/build/ImageManipulator/ImageManipulator.js' {
  declare module.exports: $Exports<'expo/build/ImageManipulator/ImageManipulator'>;
}
declare module 'expo/build/ImagePicker/ExponentImagePicker.js' {
  declare module.exports: $Exports<'expo/build/ImagePicker/ExponentImagePicker'>;
}
declare module 'expo/build/ImagePicker/ExponentImagePicker.web.js' {
  declare module.exports: $Exports<'expo/build/ImagePicker/ExponentImagePicker.web'>;
}
declare module 'expo/build/ImagePicker/ImagePicker.js' {
  declare module.exports: $Exports<'expo/build/ImagePicker/ImagePicker'>;
}
declare module 'expo/build/IntentLauncherAndroid/ExponentIntentLauncher.js' {
  declare module.exports: $Exports<'expo/build/IntentLauncherAndroid/ExponentIntentLauncher'>;
}
declare module 'expo/build/IntentLauncherAndroid/ExponentIntentLauncher.web.js' {
  declare module.exports: $Exports<'expo/build/IntentLauncherAndroid/ExponentIntentLauncher.web'>;
}
declare module 'expo/build/IntentLauncherAndroid/IntentLauncherAndroid.js' {
  declare module.exports: $Exports<'expo/build/IntentLauncherAndroid/IntentLauncherAndroid'>;
}
declare module 'expo/build/KeepAwake/ExponentKeepAwake.js' {
  declare module.exports: $Exports<'expo/build/KeepAwake/ExponentKeepAwake'>;
}
declare module 'expo/build/KeepAwake/ExponentKeepAwake.web.js' {
  declare module.exports: $Exports<'expo/build/KeepAwake/ExponentKeepAwake.web'>;
}
declare module 'expo/build/KeepAwake/index.js' {
  declare module.exports: $Exports<'expo/build/KeepAwake/index'>;
}
declare module 'expo/build/launch/AppLoading.js' {
  declare module.exports: $Exports<'expo/build/launch/AppLoading'>;
}
declare module 'expo/build/launch/AppLoadingNativeWrapper.js' {
  declare module.exports: $Exports<'expo/build/launch/AppLoadingNativeWrapper'>;
}
declare module 'expo/build/launch/registerRootComponent.js' {
  declare module.exports: $Exports<'expo/build/launch/registerRootComponent'>;
}
declare module 'expo/build/launch/registerRootComponent.web.js' {
  declare module.exports: $Exports<'expo/build/launch/registerRootComponent.web'>;
}
declare module 'expo/build/launch/RootErrorBoundary.js' {
  declare module.exports: $Exports<'expo/build/launch/RootErrorBoundary'>;
}
declare module 'expo/build/launch/SplashScreen.js' {
  declare module.exports: $Exports<'expo/build/launch/SplashScreen'>;
}
declare module 'expo/build/launch/withExpoRoot.js' {
  declare module.exports: $Exports<'expo/build/launch/withExpoRoot'>;
}
declare module 'expo/build/Linking.js' {
  declare module.exports: $Exports<'expo/build/Linking'>;
}
declare module 'expo/build/Localization.js' {
  declare module.exports: $Exports<'expo/build/Localization'>;
}
declare module 'expo/build/logs/format/ReactNodeFormatter.js' {
  declare module.exports: $Exports<'expo/build/logs/format/ReactNodeFormatter'>;
}
declare module 'expo/build/logs/Logs.js' {
  declare module.exports: $Exports<'expo/build/logs/Logs'>;
}
declare module 'expo/build/logs/LogSerialization.js' {
  declare module.exports: $Exports<'expo/build/logs/LogSerialization'>;
}
declare module 'expo/build/logs/RemoteConsole.js' {
  declare module.exports: $Exports<'expo/build/logs/RemoteConsole'>;
}
declare module 'expo/build/logs/RemoteLogging.js' {
  declare module.exports: $Exports<'expo/build/logs/RemoteLogging'>;
}
declare module 'expo/build/logs/symbolicateStackTrace.js' {
  declare module.exports: $Exports<'expo/build/logs/symbolicateStackTrace'>;
}
declare module 'expo/build/logs/symbolicateStackTrace.web.js' {
  declare module.exports: $Exports<'expo/build/logs/symbolicateStackTrace.web'>;
}
declare module 'expo/build/MailComposer/ExponentMailComposer.js' {
  declare module.exports: $Exports<'expo/build/MailComposer/ExponentMailComposer'>;
}
declare module 'expo/build/MailComposer/ExponentMailComposer.web.js' {
  declare module.exports: $Exports<'expo/build/MailComposer/ExponentMailComposer.web'>;
}
declare module 'expo/build/MailComposer/MailComposer.js' {
  declare module.exports: $Exports<'expo/build/MailComposer/MailComposer'>;
}
declare module 'expo/build/MailComposer/MailComposer.types.js' {
  declare module.exports: $Exports<'expo/build/MailComposer/MailComposer.types'>;
}
declare module 'expo/build/Notifications/ExponentNotifications.js' {
  declare module.exports: $Exports<'expo/build/Notifications/ExponentNotifications'>;
}
declare module 'expo/build/Notifications/ExponentNotifications.web.js' {
  declare module.exports: $Exports<'expo/build/Notifications/ExponentNotifications.web'>;
}
declare module 'expo/build/Notifications/Notifications.js' {
  declare module.exports: $Exports<'expo/build/Notifications/Notifications'>;
}
declare module 'expo/build/Payments.js' {
  declare module.exports: $Exports<'expo/build/Payments'>;
}
declare module 'expo/build/Pedometer.js' {
  declare module.exports: $Exports<'expo/build/Pedometer'>;
}
declare module 'expo/build/ScreenOrientation/ExponentScreenOrientation.js' {
  declare module.exports: $Exports<'expo/build/ScreenOrientation/ExponentScreenOrientation'>;
}
declare module 'expo/build/ScreenOrientation/ExponentScreenOrientation.web.js' {
  declare module.exports: $Exports<'expo/build/ScreenOrientation/ExponentScreenOrientation.web'>;
}
declare module 'expo/build/ScreenOrientation/ScreenOrientation.js' {
  declare module.exports: $Exports<'expo/build/ScreenOrientation/ScreenOrientation'>;
}
declare module 'expo/build/SecureStore/ExponentSecureStore.js' {
  declare module.exports: $Exports<'expo/build/SecureStore/ExponentSecureStore'>;
}
declare module 'expo/build/SecureStore/ExponentSecureStore.web.js' {
  declare module.exports: $Exports<'expo/build/SecureStore/ExponentSecureStore.web'>;
}
declare module 'expo/build/SecureStore/SecureStore.js' {
  declare module.exports: $Exports<'expo/build/SecureStore/SecureStore'>;
}
declare module 'expo/build/Speech/ExponentSpeech.js' {
  declare module.exports: $Exports<'expo/build/Speech/ExponentSpeech'>;
}
declare module 'expo/build/Speech/ExponentSpeech.web.js' {
  declare module.exports: $Exports<'expo/build/Speech/ExponentSpeech.web'>;
}
declare module 'expo/build/Speech/Speech.js' {
  declare module.exports: $Exports<'expo/build/Speech/Speech'>;
}
declare module 'expo/build/Speech/Speech.types.js' {
  declare module.exports: $Exports<'expo/build/Speech/Speech.types'>;
}
declare module 'expo/build/SQLite.js' {
  declare module.exports: $Exports<'expo/build/SQLite'>;
}
declare module 'expo/build/SQLite.web.js' {
  declare module.exports: $Exports<'expo/build/SQLite.web'>;
}
declare module 'expo/build/StoreReview/ExponentStoreReview.js' {
  declare module.exports: $Exports<'expo/build/StoreReview/ExponentStoreReview'>;
}
declare module 'expo/build/StoreReview/ExponentStoreReview.web.js' {
  declare module.exports: $Exports<'expo/build/StoreReview/ExponentStoreReview.web'>;
}
declare module 'expo/build/StoreReview/StoreReview.js' {
  declare module.exports: $Exports<'expo/build/StoreReview/StoreReview'>;
}
declare module 'expo/build/Svg.js' {
  declare module.exports: $Exports<'expo/build/Svg'>;
}
declare module 'expo/build/Svg.web.js' {
  declare module.exports: $Exports<'expo/build/Svg.web'>;
}
declare module 'expo/build/takeSnapshotAsync.js' {
  declare module.exports: $Exports<'expo/build/takeSnapshotAsync'>;
}
declare module 'expo/build/timer/polyfillNextTick.js' {
  declare module.exports: $Exports<'expo/build/timer/polyfillNextTick'>;
}
declare module 'expo/build/Updates/ExponentUpdates.js' {
  declare module.exports: $Exports<'expo/build/Updates/ExponentUpdates'>;
}
declare module 'expo/build/Updates/ExponentUpdates.web.js' {
  declare module.exports: $Exports<'expo/build/Updates/ExponentUpdates.web'>;
}
declare module 'expo/build/Updates/Updates.js' {
  declare module.exports: $Exports<'expo/build/Updates/Updates'>;
}
declare module 'expo/build/Util.js' {
  declare module.exports: $Exports<'expo/build/Util'>;
}
declare module 'expo/build/web/Network/RCTNetworking.js' {
  declare module.exports: $Exports<'expo/build/web/Network/RCTNetworking'>;
}
declare module 'expo/build/web/Performance/Systrace.js' {
  declare module.exports: $Exports<'expo/build/web/Performance/Systrace'>;
}
declare module 'expo/build/web/Utilities/HMRLoadingView.js' {
  declare module.exports: $Exports<'expo/build/web/Utilities/HMRLoadingView'>;
}
declare module 'expo/build/WebBrowser/ExponentWebBrowser.js' {
  declare module.exports: $Exports<'expo/build/WebBrowser/ExponentWebBrowser'>;
}
declare module 'expo/build/WebBrowser/ExponentWebBrowser.web.js' {
  declare module.exports: $Exports<'expo/build/WebBrowser/ExponentWebBrowser.web'>;
}
declare module 'expo/build/WebBrowser/WebBrowser.js' {
  declare module.exports: $Exports<'expo/build/WebBrowser/WebBrowser'>;
}
declare module 'expo/tools/hashAssetFiles.js' {
  declare module.exports: $Exports<'expo/tools/hashAssetFiles'>;
}
declare module 'expo/tools/LogReporter.js' {
  declare module.exports: $Exports<'expo/tools/LogReporter'>;
}
